CREATE TABLE users (
       id SERIAL PRIMARY KEY,
       created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
       token VARCHAR(256) UNIQUE,
       name VARCHAR(256) NOT NULL
)
